CREATE TABLE CLAIM_HISTORY
(
  CLAIM_ID     CHAR(10)     NOT NULL,
  POLICY_NO    CHAR(10)     NOT NULL,
  CLAIM_AMOUNT DECIMAL(9,2) NOT NULL,
  CLAIM_DATE   DATE         NOT NULL,
  STATUS       CHAR(1)      NOT NULL,
  PRIMARY KEY (CLAIM_ID)
);
